config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'late'
      'danger'
    when 'complete'
      'success'
    end
  end

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Projeto criado com sucesso." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Projeto atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Projeto foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :deadline)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :deadline, class: 'form-label' %>
    <%= form.date_select :deadline, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Criar Projeto', class: 'btn btn-primary' %>
  </div>


<% end %>

app/views/projects/edit.html.erb
<%= link_to 'Voltar', @project, class: 'btn btn-secondary mb-3' %>
<div class="card">
    <div class="card-body">
      <h2 class="card-title mb-4">
        <span>Editar Projeto</span>
      </h2>

      <%= render 'form', project: @project %>
    </div>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span>Projetos</span>
      <%= link_to new_project_path, class: 'btn btn-primary' do %>Novo Projeto<% end %>
    </h2>

    <% @projects.each do |project| %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">
          <div class="card-body">
            <span class="badge alert-<%= project.badge_color%>">
              <%= project.status %> 
            </span>
            <span class="text-secondary">
              <small><%= project.percent_complete%>% concluído
              (<%= project.total_complete %>/<% project.total_tasks %> tarefas)
              - <%= project.created_at.strftime('%B %d, %Y') %>
              </small>
              
            </span>
            <h5 class="card-title text-dark"><b><%= project.name %></b></h5>
            <p class="text-secondary"><%= project.description %></p>

          </div>
        </div>
      <% end %>
    <% end %>    
  </div>
</div>

app/views/projects/new.html.erb
<%= link_to 'Voltar', projects_path, class: 'btn btn-secondary mb-3' %>
<div class="card">
    <div class="card-body">
      <h2 class="card-title mb-4">
        <span>Novo Projeto</span>
      </h2>

      <%= render 'form', project: @project %>
    </div>
</div>

app/views/projects/show.html.erb
<%= link_to 'Voltar', projects_path, class: 'btn btn-info mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span><%= @project.name %></span>
      <div>
        <%= link_to 'Editar', edit_project_path(@project), class: 'btn btn-light' %> 
        <%= link_to 'Apagar', @project, method: :delete, class: 'btn btn-secondary', data: { confirm: 'Você tem certeza?' } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Nova tarefa</h6>

      <%= form_for([@task.project, @task]) do |f| %> <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@task.errors.count, "error") %> prohibited this task
          from being saved:
        </h2>

        <ul>
          <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <%= f.hidden_field :status, value: 'ocioso' %>
      <div class="input-group">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Nome da tarefa...' %>
        <div class="input-group-append">
          <%= f.submit 'Criar Tarefa', class: 'btn btn-primary' %>
        </div>
      </div>
      <% end %>
    </div>

    <h4>Tarefas</h4>
    <% @project.tasks.each do |task| %> 
      <% if task.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <span class="badge alert-<%= task.badge_color %> mb-3"><%= task.status %></span>
            <h5 class="card-title d-flex justify-content-between mb-2">
              <span><%= task.name %></span>
              <div>
              <%= link_to 'Editar', edit_project_task_path(task.project, task), class: 'btn btn-light btn-sm' %>
              <%= link_to 'Apagar', [task.project, task], method: :delete, data: {confirm: 'Você tem certeza?' }, class: 'btn btn-dark btn-sm' %>
              </div>
            </h5>
            <p><%= task.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>